package com.maybenot.oeh.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@DynamoDBTable(tableName = "places")
@Data
public class Place {

    @DynamoDBHashKey(attributeName = "placeId")
    @DynamoDBAutoGeneratedKey
    private String placeId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName = "coordinate")
    private Coordinate coordinate;

    @Data
    public static class Coordinate {

        @DynamoDBAttribute(attributeName = "longitude")
        private Double longitude;

        @DynamoDBAttribute(attributeName = "latitude")
        private Double latitude;
    }
}
